# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  tags:
    include:
      - v*
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    version: 3.0.100-rc1-014190

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- powershell: mv '$(Build.ArtifactStagingDirectory)/a.zip' '$(Build.ArtifactStagingDirectory)/VncMatrix.zip'

- powershell: tree '$(Build.ArtifactStagingDirectory)' /F
  
- powershell: $t = '$(Build.SourceBranch)'.Substring(10); echo "##vso[task.setvariable variable=value;isOutput=true]$t"
  name: GetGithubTag

- powershell: echo $(GetGithubTag.value)

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'VncDotnet'
    action: 'edit'
    #target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tag: $(GetGithubTag.value)
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    assets: '$(Build.ArtifactStagingDirectory)/*' # Optional
    assetUploadMode: 'replace'
    #isDraft: false # Optional
    #isPreRelease: false # Optional
    #addChangeLog: true # Optional
    #compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
    #releaseTag: # Required when compareWith == LastReleaseByTag
